# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Altman & Berg
description: "Wine Market Insight Publication"
baseurl: "/"
url: "http://gasparlg.github.io/altmanbergtest2"
tagline: "Wine Market Insight"


# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
gems: [jekyll-paginate]
paginate: 6
paginate_path: '/blog/page:num/'
permalink: /:title